-- Addon classification (in addition to taste_type for pancakes)
ALTER TABLE public.addon
  ADD COLUMN IF NOT EXISTS addon_kind text;

ALTER TABLE public.addon
  DROP CONSTRAINT IF EXISTS addon_addon_kind_check;

ALTER TABLE public.addon
  ADD CONSTRAINT addon_addon_kind_check CHECK (
    addon_kind IS NULL
    OR addon_kind IN (
      'pancake_sweet',
      'pancake_savory',
      'tortilla_meat',
      'tortilla_spread',
      'none'
    )
  );

-- Per-product addon groups (e.g. Meso / Namaz for tortillas)
CREATE TABLE IF NOT EXISTS public.product_addon_slot (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.product (id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  label text NOT NULL DEFAULT '',
  max_select integer NOT NULL DEFAULT 3 CHECK (max_select >= 1 AND max_select <= 20),
  UNIQUE (product_id, sort_order)
);

CREATE INDEX IF NOT EXISTS product_addon_slot_product_id_idx
  ON public.product_addon_slot (product_id);

CREATE TABLE IF NOT EXISTS public.product_addon_slot_addon (
  slot_id bigint NOT NULL REFERENCES public.product_addon_slot (id) ON DELETE CASCADE,
  addon_id bigint NOT NULL REFERENCES public.addon (id) ON DELETE CASCADE,
  PRIMARY KEY (slot_id, addon_id)
);

CREATE INDEX IF NOT EXISTS product_addon_slot_addon_addon_id_idx
  ON public.product_addon_slot_addon (addon_id);

-- RLS: mirror open access for anon key used by app + admin cookie routes
ALTER TABLE public.product_addon_slot ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_addon_slot_addon ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "product_addon_slot_all" ON public.product_addon_slot;
CREATE POLICY "product_addon_slot_all"
  ON public.product_addon_slot
  FOR ALL
  USING (true)
  WITH CHECK (true);

DROP POLICY IF EXISTS "product_addon_slot_addon_all" ON public.product_addon_slot_addon;
CREATE POLICY "product_addon_slot_addon_all"
  ON public.product_addon_slot_addon
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Backfill pancake kinds from taste_type (Serbian labels)
UPDATE public.addon a
SET addon_kind = 'pancake_sweet'
FROM public.taste_type t
WHERE a.taste_type_id = t.id
  AND lower(t.name) LIKE '%slat%'
  AND (a.addon_kind IS NULL OR a.addon_kind = 'none');

UPDATE public.addon a
SET addon_kind = 'pancake_savory'
FROM public.taste_type t
WHERE a.taste_type_id = t.id
  AND lower(t.name) LIKE '%slan%'
  AND (a.addon_kind IS NULL OR a.addon_kind = 'none');

-- Tortilla products: two default slots (admin can edit addons per slot later)
INSERT INTO public.product_addon_slot (product_id, sort_order, label, max_select)
SELECT p.id, 0, 'Meso', 3
FROM public.product p
INNER JOIN public.product_type pt ON pt.id = p.product_type_id
WHERE lower(pt.name) LIKE '%tort%'
ON CONFLICT (product_id, sort_order) DO NOTHING;

INSERT INTO public.product_addon_slot (product_id, sort_order, label, max_select)
SELECT p.id, 1, 'Namaz', 3
FROM public.product p
INNER JOIN public.product_type pt ON pt.id = p.product_type_id
WHERE lower(pt.name) LIKE '%tort%'
ON CONFLICT (product_id, sort_order) DO NOTHING;

-- Link tortilla_* addons to Meso / Namaz slots (no rows until kinds are set in admin)
INSERT INTO public.product_addon_slot_addon (slot_id, addon_id)
SELECT pas.id, a.id
FROM public.product_addon_slot pas
INNER JOIN public.product p ON p.id = pas.product_id
INNER JOIN public.product_type pt ON pt.id = p.product_type_id
CROSS JOIN public.addon a
WHERE lower(pt.name) LIKE '%tort%'
  AND pas.sort_order = 0
  AND a.addon_kind = 'tortilla_meat'
  AND a.is_active = true
ON CONFLICT (slot_id, addon_id) DO NOTHING;

INSERT INTO public.product_addon_slot_addon (slot_id, addon_id)
SELECT pas.id, a.id
FROM public.product_addon_slot pas
INNER JOIN public.product p ON p.id = pas.product_id
INNER JOIN public.product_type pt ON pt.id = p.product_type_id
CROSS JOIN public.addon a
WHERE lower(pt.name) LIKE '%tort%'
  AND pas.sort_order = 1
  AND a.addon_kind = 'tortilla_spread'
  AND a.is_active = true
ON CONFLICT (slot_id, addon_id) DO NOTHING;
